# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2014

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: false

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  # Archives: /archives/
  Tags: /tags
  Categories: /categories
  About: /about

# site search option
search: false

# Fancybox
fancybox: true

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Mint Green

# ===========================================
# Social links Settings
# ===========================================
social:
  email: huangpeng1009@gmail.com
  stack-overflow:
  twitter: https://twitter.com/Curry_Huang
  facebook: https://www.facebook.com/curry.huang.1009
  github: https://github.com/curryhuang
  weibo: http://weibo.com/spaisp
  zhihu: 

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: e7cbcbc6c877f0f9894242ad3c946943
# Google Analytics
google_analytics: 

# Duoshuo
duoshuo_shortname: 
# Disqus
disqus_shortname: curryhuang


# ===========================================
# Version
# ===========================================
version: 2.1.x
